### ISSUE TITLE
Undable to start the npm

### ISSUE THREAD

**Issue by jeet136** [okta/samples-nodejs-express-4#126]
I have downloaded the code and also updated config.js and testenv file and then after i start the npm. I getting below error.

PS C:\Users\jitesh.rathod\Downloads\samples-nodejs-express-4-master\samples-nodejs-express-4-master> npm start
npm ERR! Missing script: "start"
npm ERR!
npm ERR! Did you mean one of these?
npm ERR!     npm star # Mark your favorite packages
npm ERR!     npm stars # View packages marked as favorites
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jitesh.rathod\AppData\Local\npm-cache\_logs\2022-07-25T06_15_51_717Z-debug-0.log
PS C:\Users\jitesh.rathod\Downloads\samples-nodejs-express-4-master\samples-nodejs-express-4-master>

**Comment by oleksandrpravosudko-okta** [comment]
@jeet136 please use npm scripts in samples' subdirectories (e.g. https://github.com/okta/samples-nodejs-express-4/tree/master/custom-login).
