### ISSUE TITLE
Running the Mock Server returns a 404

### ISSUE THREAD

**Issue by saimaddali** [okta/samples-nodejs-express-4#13]
When I run ```npm run mock-okta``` it runs fine but when I visit ```http://127.0.0.1:7777``` on the browser, it throws the following error on the console: 
![image](https://cloud.githubusercontent.com/assets/4591248/24175039/4d649278-0e51-11e7-822f-060d72715583.png)

And the browser shows the following: 
![image](https://cloud.githubusercontent.com/assets/4591248/24175053/5a707ce8-0e51-11e7-930b-9afc548d0554.png)

**Comment by johngronberg-okta** [comment]
Closing this issue. Nothing is supposed to load at 127.0.0.1:7777. Instead run npm start and go to localhost:3000
