### ISSUE TITLE
(Confusing) README for mock vs. real org

### ISSUE THREAD

**Issue by mdeggies** [okta/samples-nodejs-express-4#14]
It seems a little weird that the default instructions in the README outline how to get up and running with a mock org, and you have to scroll pretty far down the page to see the link with instructions on getting up and running with a real org. 

1) What is the point of the mock? Okta sandbox orgs are free, and we want people to register and test stuff out... :)

2) If most people are registering for Okta and testing this out using their own orgs, the default instructions in the README should outline the steps for that. The big difference between the two (mock vs real) is setting up CORS. This should be easily searchable in the main README.

**Comment by nbarbettini** [comment]
I think the mock server is pretty cool, but I agree - it makes it more confusing when someone wants to set up a real org and test it out. (And I agree with @mdeggies, that should be what we want people to ultimately do)

**Comment by mdeggies** [comment]
I think the mock is cool too, but.. another strange this is that it doesn't have a front-end. I expected the sample project to behave the same way regardless of whether I was using the mock or my own org. But if you start the mock and go to 127.0.0.1:7777, you're greeted with a 404 error.

**Comment by jmelberg-okta** [comment]
We moved away from using a mock service to emulate Okta responses. Closing this as it no longer applies.
