### ISSUE TITLE
Not Checking if the User is logged in, just looking for code.

### ISSUE THREAD

**Issue by pmcdowell-okta** [okta/samples-nodejs-express-4#22]
When a User click on the Login w/ Okta button, and get directed to okta
**,but the user is not loggged into Okta yet**  User sees an error saying
User does not have code, when the error is because they don't have
a session w/ Okta.

Error Displayed on Page: **Required query parameter "code" is missing**

``
http://localhost:3000/authorization-code/callback?state=oArfSWypYbUON2FWF0iDcvgl6qFdM0VYXSYOHvjjtCaDBQwIFn7iO5tr88jfwxLb&error=access_denied&error_description=User+is+not+assigned+to+the+client+application.
``
Check for this error in addition to the code, say User is not logged in.

**Comment by robertjd** [comment]
Closing, as this was related to the old version of this sample.  Please see the README for the latest usage, thanks!
