### ISSUE TITLE
Error when running the npm 

### ISSUE THREAD

**Issue by z017249** [okta/samples-nodejs-express-4#28]
Hello,
I am getting the following error when I execute 'npm start' from windows command line.
Kindly help.

'DIST_OUT' is not recognized as an internal or external command,
operable program or batch file.
child_process.js:524
    throw err;
    ^

Error: Command failed: DIST_OUT=D:\Public\okta\samples-nodejs-express-4-master\dist npm run build
    at checkExecSyncError (child_process.js:481:13)
    at execSync (child_process.js:521:13)
    at Object.<anonymous> (D:\Public\okta\samples-nodejs-express-4-master\node_modules\@okta\samples-js-angular-1\scripts\build-frontend.js:
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Public\\node.exe" "D:\\Public\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @okta/samples-nodejs-express-4@3.0.0 prestart: `build-frontend`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @okta/samples-nodejs-express-4@3.0.0 prestart script 'build-frontend'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @okta/samples-nodejs-express-4 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     build-frontend
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @okta/samples-nodejs-express-4
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @okta/samples-nodejs-express-4
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Public\okta\samples-nodejs-express-4-master\npm-debug.log

**Comment by robertjd** [comment]
Hi @z017249 , can you look at #18 ?  There are some workarounds proposed, I've opened that issue for us to look at soon.  Thank you!

**Comment by jmelberg-okta** [comment]
Closing this issue as it was already reported here: #18
