### ISSUE TITLE
SSL Error when running the sample

### ISSUE THREAD

**Issue by sohaibajmal-okta** [okta/samples-nodejs-express-4#48]
Following errors are returned when I try to run the sample. 

>  @okta/samples-nodejs-express-4@3.0.0 okta-hosted-login-server /Users/sohaibajmal/Documents/OktaDeveloperSamples/Okta_NodeMiddleware/samples-nodejs-express-4-master
>  node okta-hosted-login/server.js
> 
> (node:4071) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): RequestError: write EPROTO 140736950694848:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:797:
> 
> (node:4071) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Steps followed

1 - Checkout sample

2 - npm installl

3 - Update .sample.json.config with org and OIDC app information

4 - npm run custom-login-server

Node Versions Tried: 7.9.0 and 8.1.1

**Comment by robertjd** [comment]
Hi @sohaibajmal-okta , did you find the problem here with the SSL error?
