### ISSUE TITLE
Unable to Authenticate using Okta Hosted Login

### ISSUE THREAD

**Issue by digitalrinaldo** [okta/samples-nodejs-express-4#49]
We use Okta for internal Infrastructure and I have been unable to authenticate.  I am able to login and my browser redirects and ends up doing a POST to the entry point and I get a 404. I have tried two other node.js express libraries and have the same result.  One of the other libraries ends up doing constant redirects.  My issuer's urls do not follow this convention.

> Issuer - This is the URL of the authorization server that will perform authentication. All Developer Accounts have a "default" authorization server. The issuer is a combination of your Org URL (found in the upper right of the console home page) and /oauth2/default. For example, https://dev-1234.oktapreview.com/oauth2/default.

My issuer URL has the name of the app,  the issuer id and ends in sso/saml

**Comment by robertjd** [comment]
HI @digitalrinaldo , our bad for not replying sooner.  This example app is meant to example the [implicit flow](https://developer.okta.com/authentication-guide/implementing-authentication/implicit), which is an OAuth 2.0 flow.  Unfortunately we don't have similar examples for SAML flows, which is what it looks like you're trying to use here?  Please let me know if this is not the case?  I will close this issue for now, but you can re-open if needed.  Thanks!
