### ISSUE TITLE
unauthorized

### ISSUE THREAD

**Issue by hampsterx** [okta/samples-nodejs-express-4#51]
```
 hostname: 'myorg.okta.com',
  method: 'GET',
  path: '/oauth2/default/.well-known/openid-configuration',
  protocol: 'https:',
  url: 'https://myorg.okta.com/oauth2/default/.well-known/openid-configuration',
  statusCode: 401,
  statusMessage: 'Unauthorized',
```
Simply cannot get it to start correctly.

pretty sure settings are correct..

```
{
  "webServer": {
    "port": 8080,
    "oidc": {
      "clientId": "xx",
      "clientSecret": "yy",
      "issuer": "https://myorg.okta.com/oauth2/default",
      "redirectUri": "http://localhost:8080/authorization-code/callback",
      "scope": "openid profile email"
    }
  },
  "resourceServer": {
    "port": 8000,
    "oidc": {
      "issuer": "https://myorg.okta.com/oauth2/default"
    },
    "assertClaims": {
      "aud": "api://default",
      "cid": "xx"
    }
  }
}
```

any ideas?

Also, your recent changes to the admin UI the url for org is no longer shown in dashboard, I presume its https://xxx.okta.com as noted in docs that it's same as dashboard minus the "-admin".

There is additional documentation on your site that needs to be updated as well, I am thoroughly NOT enjoying the experience right now after trying this sample, my own custom one, seeing the high no of open issues on "okta-oidc-js" and reading your forums. GRR

**Comment by manueltanzi-okta** [comment]
Hi @hampsterx , thank you for your question!

Just to clarify, which one of the three samples are you trying to run?
[Okta-Hosted Login](https://github.com/okta/samples-nodejs-express-4/blob/master/okta-hosted-login) , [Custom Login Page](https://github.com/okta/samples-nodejs-express-4/blob/master/custom-login) or [Resource Server](https://github.com/okta/samples-nodejs-express-4/blob/master/resource-server)?

I am sorry you fell like that, we are working on improving our developer experience, hopefully you will enjoy it better in the future!

**Comment by trujamal** [comment]
Has this issue been resolved already, in regards to the Unauthorized message from the server? 
Following the latest docs on the Custom Login Page example.

**Comment by swiftone** [comment]
Hi @trujamal - 

We're not aware of any problem (this issue was never clarified from the reporting dev).  

From your edit it sounds like you've figured out the issue.  If you have any further issues please open a new issue with the details.
