### ISSUE TITLE
Invalid value for 'client_id' parameter.

### ISSUE THREAD

**Issue by noahrama** [okta/samples-nodejs-express-4#60]
Hi i am trying to use the sign-in widget. After i login, i get:
error 400
Error Code: invalid_client
Description: Invalid value for 'client_id' parameter. 

this is what my client ID says it is
![image](https://user-images.githubusercontent.com/4156246/50812481-09e3e400-1367-11e9-9a3c-5b860fa154b6.png)

here is the url:
```
https://dev-387826.oktapreview.com/oauth2/default/v1/authorize?nonce=8bf46ef6-5499-4a70-b3f0-7d47e49a983a&state=ec07e2cd-b82f-4cab-af57-6f252da851ec&client_id=0oaituw8sjQRYE5v60h7&redirect_uri=http%3A%2F%2Flocalhost%3A6006%2Fauthorization-code%2Fcallback&scope=openid%20profile%20email&response_type=code&sessionToken=20111wN123JyC3iCpKk15t3NrKyr6rZXfEAkzotJGGHSuHYzlmGHLSi
```
and here is my .samples.config.json ( changed client secret)
```
{
    "webServer": {
        "port": 6006,
        "oidc": {
            "clientId": "0oaituw8sjQRYE5v60h7",
            "clientSecret": "ImFQHIDDENHIDDENHIDDENHIDDENOXofajqJamb-",
            "issuer": "https://dev-387826.oktapreview.com/oauth2/default",
            "redirectUri": "http://localhost:6006/authorization-code/callback",
            "scope": "openid profile email"
        }
    }
}
```

**Comment by noahrama** [comment]
my bad

**Comment by anthonybastone** [comment]
What was the solution to this problem?  I get the same.

**Comment by noahrama** [comment]
@anthonybastone 
ClientIds are not the same, i must have deleted and created the webapp during testing, thus having a different id
